[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aptos-sdk>=0.11.0",
    "fastapi>=0.128.0",
    "google-generativeai>=0.8.6",
    "httpx>=0.28.1",
    "opik>=1.9.100",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
