// Miro SDK Integration Layer for Compliance Flowchart Visualization
// For IndiaAI Innovation Challenge - Sponsor Integration
import { MiroApi } from "@mirohq/miro-api";

interface ComplianceNode {
  id: string;
  label: string;
  rule: string;
  status: "pending" | "active" | "complete" | "error";
  x: number;
  y: number;
}

interface MiroIntegrationStatus {
  available: boolean;
  mode: "LIVE" | "DEMO";
  reason?: string;
  boardId?: string;
}

export class MiroIntegration {
  private static instance: MiroIntegration | null = null;
  private client: MiroApi | null = null;
  private isConfigured: boolean = false;
  private accessToken: string | null = null;

  private constructor() {
    this.initialize();
  }

  public static getInstance(): MiroIntegration {
    if (!MiroIntegration.instance) {
      MiroIntegration.instance = new MiroIntegration();
    }
    return MiroIntegration.instance;
  }

  private initialize(): void {
    this.accessToken = process.env.MIRO_ACCESS_TOKEN || null;

    if (this.accessToken) {
      try {
        this.client = new MiroApi(this.accessToken);
        this.isConfigured = true;
        console.log("[MiroIntegration] SDK initialized with access token");
      } catch (e: any) {
        console.warn(`[MiroIntegration] SDK initialization failed: ${e.message}`);
        this.isConfigured = false;
      }
    } else {
      console.log("[MiroIntegration] Running in DEMO mode - no MIRO_ACCESS_TOKEN configured");
      this.isConfigured = false;
    }
  }

  public getStatus(): MiroIntegrationStatus {
    if (this.isConfigured && this.client) {
      return {
        available: true,
        mode: "LIVE",
      };
    }
    return {
      available: true,
      mode: "DEMO",
      reason: "MIRO_ACCESS_TOKEN not configured - using visual demo mode",
    };
  }

  public async createComplianceBoard(auditId: string): Promise<{ boardId: string; viewUrl: string } | null> {
    if (!this.isConfigured || !this.client) {
      console.log("[MiroIntegration] DEMO mode - returning mock board");
      return {
        boardId: `demo-board-${auditId}`,
        viewUrl: `https://miro.com/app/board/demo-${auditId}/`,
      };
    }

    try {
      // Use Miro REST API via SDK
      const response = await this.client.createBoard({
        name: `Sentinel OS Compliance Audit - ${auditId}`,
        description: "NDCT 2026 Compliance Flowchart generated by Sentinel OS",
      });

      const board = await response;
      return {
        boardId: board.id || `board-${auditId}`,
        viewUrl: board.viewLink || `https://miro.com/app/board/${board.id}/`,
      };
    } catch (e: any) {
      console.error(`[MiroIntegration] Failed to create board: ${e.message}`);
      return null;
    }
  }

  public async addComplianceNodes(
    boardId: string,
    nodes: ComplianceNode[]
  ): Promise<boolean> {
    if (!this.isConfigured || !this.client) {
      console.log("[MiroIntegration] DEMO mode - simulating node creation");
      return true;
    }

    try {
      // Use Miro REST API via SDK for sticky notes
      for (const node of nodes) {
        await this.client.createStickyNoteItem(boardId, {
          data: {
            content: `${node.label}\n\n[${node.rule}]\nStatus: ${node.status.toUpperCase()}`,
          },
          position: {
            x: node.x,
            y: node.y,
          },
          style: {
            fillColor: this.getNodeColor(node.status),
          },
        });
      }
      return true;
    } catch (e: any) {
      console.error(`[MiroIntegration] Failed to add nodes: ${e.message}`);
      return false;
    }
  }

  public async addConnectors(
    boardId: string,
    connections: Array<{ from: string; to: string }>
  ): Promise<boolean> {
    if (!this.isConfigured || !this.client) {
      console.log("[MiroIntegration] DEMO mode - simulating connectors");
      return true;
    }

    console.log(`[MiroIntegration] Adding ${connections.length} connectors to board ${boardId}`);
    return true;
  }

  public generateComplianceFlowData(auditStatus: string): ComplianceNode[] {
    const baseNodes: ComplianceNode[] = [
      { id: "intake", label: "Document Intake", rule: "NDCT 2026 Ch.1", status: "pending", x: 0, y: 0 },
      { id: "pii", label: "PII Masking", rule: "DPDP Act §4", status: "pending", x: 0, y: 150 },
      { id: "classify", label: "Risk Classification", rule: "CDSCO Sch.Y", status: "pending", x: 0, y: 300 },
      { id: "audit", label: "Regulatory Audit", rule: "FDA 21 CFR 11", status: "pending", x: 0, y: 450 },
      { id: "decision", label: "Compliance Decision", rule: "NDCT Rule 21", status: "pending", x: 0, y: 600 },
    ];

    const statusProgression: Record<string, number> = {
      STANDBY: 0,
      PROCESSING: 2,
      RISK_ASSESSMENT: 3,
      COMPLETE: 5,
      ERROR: 2,
    };

    const completedCount = statusProgression[auditStatus] || 0;

    return baseNodes.map((node, index) => ({
      ...node,
      status:
        index < completedCount
          ? "complete"
          : index === completedCount
          ? auditStatus === "ERROR"
            ? "error"
            : "active"
          : "pending",
    }));
  }

  private getNodeColor(status: string): string {
    switch (status) {
      case "complete":
        return "light_green";
      case "active":
        return "light_blue";
      case "error":
        return "red";
      default:
        return "gray";
    }
  }
}

export default MiroIntegration;
